### PR TITLE
Add dynamical model of ARDrone

### PR DESCRIPTION
**Pull request by lkumar93**
I have added ARDrone's model. I would like to refactor everything in this repo to replicate ethz-asl's RotorS Simulator so that we can do Software In The Loop testing and Hardware In The Loop testing .

### CODE REVIEW

**Comment by ncos** [comment]
The commit contained a code, that could not be launched - you were missing "/urdf/component_snippets.xacro'', and you have not added the dependency on 'rotors_simulator'. Why did you copy their config files, while we could just use their code in our project as a dependency?

Anyway, since we have decided to keep our 'master' clean, I had to remove your commits, sorry. Can you please make a launchable thing and then submit a pull request?

**Comment by lkumar93** [comment]
Can you create a branch called feature/simulator and merge this pull request to that branch. I will keep working on that branch

**Comment by ncos** [comment]
The idea is that people work in their own fork in a separate branch, then pull their branch into the main master. We could allow development branches in the main repo, but that would create an unnecessary mess of half-merged branches with random ugly names created for any particular development idea people might have at the moment. It is a common practice to have only master in main repo, and mark releases with tags. Check out [this](https://github.com/PointCloudLibrary/pcl) and [this](https://github.com/torvalds/linux) for example.

**Comment by lkumar93** [comment]
Oh okay fine . But what if two or more people work on the same feature
together? BTW, I think we should integrate Travis CI build farm with the
repository .

**Comment by ncos** [comment]
When people work together they pull code from each other, then one of them (the first one to have a working thing) creates a pull request. Keep in mind, that it is not important who makes a pull request, your commits will be marked with your name. It is relatively easy to keep track on who does what [here](https://github.com/cognifli/cognifli/network), by looking at branch names. For that (and some other reasons) people never develop in their own master, but rather keep their master in sync with main repo master while developing in a separate branch. I see you have put your commit in your master, you can fix that by 'rebasing' it in a new branch, or collaboration with other people might be problematic (keeping a synked master really helps when you have to work on a separate task).

I will look into Travis CI

BTW, how exactly are you going to test the simulation?

**Comment by lkumar93** [comment]
Ideally it should replicate the behaviour of a quadrotor in the real world

**Comment by ncos** [comment]
You wanted Software/Hardware In The Loop. How are you going to do that for Gazebo simulation?)

**Comment by lkumar93** [comment]
It will be based on something like this
http://dev.px4.io/simulation-sitl.html . Qualcomm snapdragon uses px4 stack
, so it would be easy to integrate.

**Comment by ncos** [comment]
Ok. I have approved the request for Travis CI. Someone has to write a configuration file however)

**Comment by lkumar93** [comment]
I will do it

**Comment by ncos** [comment]
OK, Thanks!

**Pull request merged**
